#
# Lasso
#
# Implements the ability to unleash an entity from a post to the player
# and leash additional mobs
#

lasso:

  # allow to be leashed only if player has the lasso.<mob> permission
  perms: false

  # allow to be leashed if mob on this list (some mobs might not able to be leashed)
  mobs:
    - BAT
    - BEE
    - BLAZE
    - CAT
    - CAVE_SPIDER
    - CHICKEN
    - COD
    - COW
    - CREEPER
    - DOLPHIN
    - DONKEY
    - DROWNED
    - ELDER_GUARDIAN
    - ENDER_DRAGON
    - ENDERMAN
    - ENDERMITE
    - EVOKER
    - FOX
    - GHAST
    - GIANT
    - GUARDIAN
    - HOGLIN
    - HORSE
    - HUSK
    - ILLUSIONER
    - IRON_GOLEM
    - LLAMA
    - MAGMA_CUBE
    - MULE
    - MUSHROOM_COW
    - OCELOT
    - PANDA
    - PARROT
    - PHANTOM
    - PIG
    - PIGLIN
    - PILLAGER
    - PLAYER
    - POLAR_BEAR
    - PUFFERFISH
    - RABBIT
    - RAVAGER
    - SALMON
    - SHEEP
    - SHULKER
    - SILVERFISH
    - SKELETON
    - SKELETON_HORSE
    - SLIME
    - SNOWMAN
    - SPIDER
    - SQUID
    - STRAY
    - STRIDER
    - TRADER_LLAMA
    - TROPICAL_FISH
    - TURTLE
    - VEX
    - VILLAGER
    - VINDICATOR
    - WANDERING_TRADER
    - WITCH
    - WITHER
    - WITHER_SKELETON
    - WOLF
    - ZOGLIN
    - ZOMBIE
    - ZOMBIE_HORSE
    - ZOMBIE_VILLAGER
    - ZOMBIFIED_PIGLIN
